### ISSUE TITLE
Spin Cloud Deploy - CLI response feedback  

### ISSUE THREAD

**Issue by flynnduism** [fermyon/cloud-plugin#152]
When I deploy an app I see this success message:

```
Deploying...
Waiting for application to become ready... ready
Available Routes:
  fileserver: https://fw2.fermyon.app (wildcard)
```

**Terminology**
This information about component routes lists things in a similar way to what spin does locally with `spin up` (talking about fileserver, routes). Because this app is now deployed and publicly available, the terminology here might reflect that?

**Cloud URL**
It would be nice to reference the management URL for the app in the new structure of the Cloud UI, i.e. `https://cloud.fermyon.com/app/<appname>/` 

E.g. deploy success could look something like

```
Deploying...
Waiting for application to become ready... ready

Available Routes:
  View application:         https://fw2.fermyon.app (wildcard)
  Manage application:       https://cloud.fermyon.com/app/<appname>/

  ^                         ^ (bonus points for tabular indentation formatting)
```

**Comment by itowlson** [comment]
Ooh I like the idea of linking to the app settings.

For the "view application", is the proposal that we show only the application root (the subdomain), even if the app contains multiple components mounted at different routes?  (It's not a problem to do so; just clarifying the desired UI.)

**Comment by itowlson** [comment]
What if we always printed the "View application" base URL and then printed the component routes only if there was at least one route that wasn't a blanket?  E.g.

```
# Just one blanket route
ivan@hecate:~/testing/dbmadness$ spin cloud deploy
Uploading dbmadness version 0.1.0 to Fermyon Cloud...
Deploying...
Waiting for application to become ready.......... ready

View application:   https://dbmadness-hyi1xhfs.fermyon.app/
Manage application: https://cloud.fermyon.com/app/dbmadness

# Multiple routes
ivan@hecate:~/testing/dbmadness$ spin cloud deploy
Uploading dbmadness version 0.1.0 to Fermyon Cloud...
Deploying...
Waiting for application to become ready.................. ready

View application:   https://dbmadness-hyi1xhfs.fermyon.app/
  Routes:
  - dbmadness: https://dbmadness-hyi1xhfs.fermyon.app (wildcard)
    Absolute madness, you'll laugh, you'll cry. But with DATABASES
  - dbmadness: https://dbmadness-hyi1xhfs.fermyon.app/bibble
    Absolute madness, you'll laugh, you'll cry. But with DATABASES
Manage application: https://cloud.fermyon.com/app/dbmadness
```

That said, one common case for this is a blanket that represents the app, and a fileserver to provide the assets.  And the user is unlikely to be particularly interested in the fileserver route.  (Let alone if there are large numbers of redirects.)

Maybe I'll send a PR because it will be easy to rip out the routes stuff if you dislike it.
