### ISSUE TITLE
Simplify local build cycle

### ISSUE THREAD

**Issue by itowlson** [fermyon/cloud-plugin#36]
The current instructions for local build and test seem quite manual - would we be open to having an option for `spin pluginify` (https://github.com/itowlson/spin-pluginify) for local dev?  How about if it were in the official plugins registry?

**Comment by itowlson** [comment]
Though it won't currently work because the binary name is different from the plugin name.

**Comment by vdice** [comment]
Oh shoot, as I so often do, I worked on an approach for this _and then_ took a gander at the issue queue 😂 

I'd be willing to update https://github.com/fermyon/cloud-plugin/pull/60 to use spin-pluginify if you think we can get over the hurdle mentioned in https://github.com/fermyon/cloud-plugin/issues/36#issuecomment-1603503426.

**Comment by itowlson** [comment]
@vdice spin-pluginify accepts pull requests _grin_ - I think it already knows the plugin name so it should be easy to tweak it to rename a mismatched input binary during tarring?  Other ways to make it compatible without changing spin-pluginify:

* Retain the current "copy the binary to have the plugin name" command, and use the copied location in the pluginify manifest
* Change the name in this project's Cargo.toml from `cloud-plugin` to `cloud` so it already has the right name

**Comment by vdice** [comment]
Closed by https://github.com/fermyon/cloud-plugin/pull/72
