### ISSUE TITLE
`prompt_for_auth_method` offers invalid option (and ticks user off when they choose it)

### ISSUE THREAD

**Issue by itowlson** [fermyon/cloud-plugin#38]
from https://github.com/fermyon/installer/issues/128

If the user runs `spin login --url` (which is still allowed), it drops them `prompt_for_auth_method` (https://github.com/fermyon/cloud-plugin/blob/main/src/commands/login.rs#L430-L442).

This asks them to choose 1 or 2.  If they choose 2, it prints "invalid input" and asks again.

**Comment by bacongobbler** [comment]
This will be fixed with https://github.com/fermyon/cloud-plugin/pull/33.

**Comment by radu-matei** [comment]
Fixed in #33.
