### ISSUE TITLE
Release action consistently fails

### ISSUE THREAD

**Issue by itowlson** [fermyon/cloud-plugin#39]
https://github.com/fermyon/cloud-plugin/actions/workflows/release.yml

It's having a problem overwriting the canary release asset.

![image](https://github.com/fermyon/cloud-plugin/assets/865538/7f4906da-d25d-4fbc-92bc-963ef6fe9fa3)

**Comment by vdice** [comment]
We've serialized the release workflow runs in https://github.com/fermyon/cloud-plugin/pull/62 and believe this is the main fix needed here.  Closing for now, but let's re-open if we encounter the same behavior again.
