### ISSUE TITLE
remove bindle flags from spin deploy

### ISSUE THREAD

**Issue by michelleN** [fermyon/cloud-plugin#41]
--buildinfo, --no-buildinfo , -d/-staging-dir and -e/--deploy-existing-bindle

**Comment by itowlson** [comment]
`--staging-dir` and `--deploy-existing-bindle` are gone.  Do we also want to remove `--buildinfo` and `--no-buildinfo`?  Currently it seems like the buildinfo is appended to the version part of the OCI tag (e.g. `cloud.fermyon.com:myspiffyapp:0.0.1-buildinfo`) but I am not sure if that's useful given that OCI tags are mutable?

If we think buildinfo is not useful, should we also remove the random buildinfo?  Again I am not sure if it is significant e.g. for application URLs.

**Comment by itowlson** [comment]
Well `--no-buildinfo` crashes the deployment process after uploading the app so that one can get in the sea

**Comment by vdice** [comment]
😬 Yes, let's remove both.

**Comment by itowlson** [comment]
![Exterminate](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.tenor.com%2Fimages%2Fbac8c1709595b426ebf94007e14c69cd%2Ftenor.gif&f=1&nofb=1&ipt=4ab874cd5abf2f535e669ce9a4152cc07fce1d90354b29ea5017d0734f18c54e&ipo=images)

**Comment by itowlson** [comment]
Should we still create the random suffix or can I exterminate that too?

**Comment by vdice** [comment]
> Should we still create the random suffix or can I exterminate that too?

Again, I'm pretty sure it isn't used in any of our app check/ready logic, so should be good to remove.  I can help verify/test when PR is up.
