### ISSUE TITLE
Inform users how to join SQLite private beta

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/cloud-plugin#55]
it would be good to do some pre-deployment validation to help give users information to sign-up for SQLite private beta. We could bake this into `spin cloud deploy` as @macolso suggests: 

```sh
NoOps SQL DB is currently in private beta. Please visit our developer documentation for instructions on how to request access: https://developer.fermyon.com/cloud/noops-sql-db
```

**Comment by lann** [comment]
This would also be helpful for the `spin cloud sqlite` subcommands, which apparently will currently just fail with:

```console
❯ spin cloud sqlite list
Error: Problem listing databases

Caused by:
    Exception of type 'Nimbus.Application.Exceptions.ForbiddenAccessException' was thrown.
```

**Comment by itowlson** [comment]
Is this now moot?

**Comment by macolso** [comment]
Yes, we should close this
