### ISSUE TITLE
`spin login` fails on WSL with `/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found`

### ISSUE THREAD

**Issue by janpio** [fermyon/cloud-plugin#87]
I just installed Spin in WSL (Ubuntu 20.04 on Windows), and am getting this error on `spin login`:

```
/home/janpio/.local/share/spin/plugins/cloud/cloud: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/janpio/.local/share/spin/plugins/cloud/cloud)
```

Am I doing it wrong (besides using Windows...)?
Any idea how I can overcome this?

---

* Spin version (`spin --version`): `spin 1.5.0 (ca08dd9 2023-09-13)`
* Installed plugin versions (`spin plugins list --installed`): 
```
cloud 0.2.0 [installed]
js2wasm 0.6.0 [installed]
py2wasm 0.3.0 [installed]
```

**Comment by karthik2804** [comment]
Hey @janpio, I have transferred the issue to the appropriate repo. It looks like the `cloud` plugin is being built using `ubuntu 22.04` which produces binaries incompatible with `ubuntu 20.04`. I have opened a PR to fix it.

**Comment by karthik2804** [comment]
@janpio We have just merged a fix - you can install the canary plugin using the following command

```bash
spin plugins install -u https://github.com/fermyon/cloud-plugin/releases/download/canary/cloud.json --yes
```

**Comment by janpio** [comment]
Yay, that worked:

```
janpio@Surface-Studio:~$ ./spin login

Copy your one-time code:

...
```

Thanks for the quick fix!

(And also for moving the issue, I was not suuuuper sure which part was doing things here - but now I of course see `spin/plugins/cloud`. Thanks.)
