### ISSUE TITLE
Build broken on nightly

### ISSUE THREAD

**Issue by lann** [fermyon/cloud-plugin#90]
Ran into this accidentally while trying to fix the same (?) problem with `cloud-start`:

```
error[E0635]: unknown feature `proc_macro_span_shrink`
```

Seems to be this bug in `proc-macro2`: https://github.com/dtolnay/proc-macro2/issues/398

...but `cargo update -p proc-macro2` causes a whole host of other errors, so it looks like fixing this one might be harder than [fixing `cloud-start`](https://github.com/fermyon/cloud-start/pull/13).

**Comment by itowlson** [comment]
Fixed via #93 and #98.
